version: '3.7'

volumes:
  my_volume:
    external: true

networks:
  mynet:
    external: true

services:

  prometheus:
    image: registry.datacommand.co.kr/prometheus:HEAD
    volumes:
      - my_volume:/prometheus
    networks:
      - mynet

  node-exporter:
    image: registry.datacommand.co.kr/node-exporter:HEAD
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - mynet
    deploy:
      mode: global

    cadvisor:
      image: registry.datacommand.co.kr/cadvisor:HEAD
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      networks:
        - mynet
      deploy:
        mode: global
