version: '3.7'

volumes:
  my_volume:
    external: true

networks:
  mynet:
    external: true

services:

  prometheus:
    image: registry.datacommand.co.kr/prometheus:HEAD
    volumes:
      - my_volume:/prometheus:rw
    ports:
      - 9090:9090
    networks:
      - mynet